export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';
export const PASSWORD_CHANGE_LOGOUT_SUCCESS= 'PASSWORD_CHANGE_LOGOUT_SUCCESS';


export const CART_UPDATE= 'CART_UPDATE';

export const CART_ADD ='CART_ADD';

export const CART_DELETE='CART_DELETE';